import os

INTERNAL_CONSUMER_TOPIC = 'INTERNAL_CONSUMER'
SUBSCRIBE_TOPIC = 'subscribe_topics'
CONSUME_MESSAGE = 'consume_message'

MAX_POLL_DELAY = 10
MIN_POLL_DELAY = 0.5

MAX_RECORDS_PER_POLL = 200
MAX_MESSAGES_PER_CONSUMER = 1000
MAX_CONSUMERS = os.cpu_count() * 5

HEARTBEAT_INTERVAL = 5
