INTERNAL_CONSUMER_TOPIC = 'INTERNAL_CONSUMER'
SUBSCRIBE_TOPIC = 'subscribe_topics'
CONSUME_MESSAGE = 'consume_message'

MAX_POLL_DELAY = 5
MIN_POLL_DELAY = 0.5

MAX_RECORDS_PER_POLL = 500
MAX_MESSAGES_PER_CONSUMER = 10000
MAX_CONSUMERS = 10
