version: '3.7'
services:
  app:
    image: kafka_streaming_pipeline
    container_name: kafka_streaming_pipeline
    build:
      context: .
      dockerfile: Dockerfile
    command:
      gunicorn app:api -b unix:/data_streaming_pipeline/datastreaming.sock -w 2
    volumes:
      - socket_data:/data_streaming_pipeline
  nginx:
    image: kafka_streaming_server
    build:
      context: conf/nginx/
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - app
    volumes:
      - socket_data:/data_streaming_pipeline
volumes:
  socket_data:
